// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: users.proto

package users

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Users service

type UsersService interface {
	GetAllUser(ctx context.Context, in *GetAllUserReq, opts ...client.CallOption) (*GetAllUserResp, error)
	GetUser(ctx context.Context, in *GetUserReq, opts ...client.CallOption) (*GetUserResp, error)
	CreateUser(ctx context.Context, in *CreUserReq, opts ...client.CallOption) (*CreUserResp, error)
	ValidateUser(ctx context.Context, in *ValidReq, opts ...client.CallOption) (*ValidRsp, error)
}

type usersService struct {
	c    client.Client
	name string
}

func NewUsersService(name string, c client.Client) UsersService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "users"
	}
	return &usersService{
		c:    c,
		name: name,
	}
}

func (c *usersService) GetAllUser(ctx context.Context, in *GetAllUserReq, opts ...client.CallOption) (*GetAllUserResp, error) {
	req := c.c.NewRequest(c.name, "Users.GetAllUser", in)
	out := new(GetAllUserResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersService) GetUser(ctx context.Context, in *GetUserReq, opts ...client.CallOption) (*GetUserResp, error) {
	req := c.c.NewRequest(c.name, "Users.GetUser", in)
	out := new(GetUserResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersService) CreateUser(ctx context.Context, in *CreUserReq, opts ...client.CallOption) (*CreUserResp, error) {
	req := c.c.NewRequest(c.name, "Users.CreateUser", in)
	out := new(CreUserResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersService) ValidateUser(ctx context.Context, in *ValidReq, opts ...client.CallOption) (*ValidRsp, error) {
	req := c.c.NewRequest(c.name, "Users.ValidateUser", in)
	out := new(ValidRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Users service

type UsersHandler interface {
	GetAllUser(context.Context, *GetAllUserReq, *GetAllUserResp) error
	GetUser(context.Context, *GetUserReq, *GetUserResp) error
	CreateUser(context.Context, *CreUserReq, *CreUserResp) error
	ValidateUser(context.Context, *ValidReq, *ValidRsp) error
}

func RegisterUsersHandler(s server.Server, hdlr UsersHandler, opts ...server.HandlerOption) error {
	type users interface {
		GetAllUser(ctx context.Context, in *GetAllUserReq, out *GetAllUserResp) error
		GetUser(ctx context.Context, in *GetUserReq, out *GetUserResp) error
		CreateUser(ctx context.Context, in *CreUserReq, out *CreUserResp) error
		ValidateUser(ctx context.Context, in *ValidReq, out *ValidRsp) error
	}
	type Users struct {
		users
	}
	h := &usersHandler{hdlr}
	return s.Handle(s.NewHandler(&Users{h}, opts...))
}

type usersHandler struct {
	UsersHandler
}

func (h *usersHandler) GetAllUser(ctx context.Context, in *GetAllUserReq, out *GetAllUserResp) error {
	return h.UsersHandler.GetAllUser(ctx, in, out)
}

func (h *usersHandler) GetUser(ctx context.Context, in *GetUserReq, out *GetUserResp) error {
	return h.UsersHandler.GetUser(ctx, in, out)
}

func (h *usersHandler) CreateUser(ctx context.Context, in *CreUserReq, out *CreUserResp) error {
	return h.UsersHandler.CreateUser(ctx, in, out)
}

func (h *usersHandler) ValidateUser(ctx context.Context, in *ValidReq, out *ValidRsp) error {
	return h.UsersHandler.ValidateUser(ctx, in, out)
}
